// Optimized Three.js imports - only what we need
export {
	WebGLRenderer,
	Scene,
	OrthographicCamera,
	Camera,
	PlaneGeometry,
	Mesh,
	RawShaderMaterial,
	Vector2,
	Vector3,
	Vector4,
	Color,
	TextureLoader,
	VideoTexture,
	LinearFilter,
	RGBFormat,
	DataTexture,
	RGBAFormat,
	ClampToEdgeWrapping,
	WebGLRenderTarget,
	HalfFloatType,
	FloatType,
	BufferGeometry,
	BufferAttribute,
	LineSegments,
	AdditiveBlending,
	Timer
} from 'three';
